version: "2"
services:
  happa:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: happa-dev:latest
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - "./src:/usr/src/app/src"
    links:
      - passage

  passage:
    image: registry.giantswarm.io/giantswarm/passage:latest
    ports:
      - "5001:5000"

    environment:
      DEBUGGING: 1
      HAPPA_BASE_URI: http://docker.dev:8000
      GIANTSWARM_API_URI: http://giantswarmmockapi:8000
      GIANTSWARM_API_TOKEN: valid_token
      HUBSPOT_API_URI: http://hubspotmock:9999
      HUBSPOT_HUB_ID: "430224"
      HUBSPOT_API_KEY: 1234567890abcdefghijklmnop
      #NUM_PROXIES: "0"
      RATELIMIT_GLOBAL: 1000 per day, 100 per hour, 30 per minute
      RATELIMIT_STORAGE_URL: redis://redis:6379

    links:
      - hubspotmock
      - giantswarmmockapi
      - redis:redis
      - mailcatcher:mailcatcher

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  # Mocks the HubSpot API
  hubspotmock:
    image: registry.giantswarm.io/giantswarm/mock-hubspot-api:latest
    environment:
      DEBUGGING: 1
    ports:
      - "9999:9999"
  giantswarmmockapi:
    image: registry.giantswarm.io/giantswarm/mock-api:latest
    environment:
      DELAY_MS: 200
    ports:
      - "9000:8000"

  mailcatcher:
    image: registry.giantswarm.io/giantswarm/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"

  desmotes:
    image: registry.giantswarm.io/giantswarm/desmotes:latest
    ports:
      - "9001:5000"
    environment:
      GIANTSWARM_API_URI: http://giantswarmmockapi:8000
      PROMETHEUS_URI: http://prometheus:9090
      PROMETHEUS_QUERY_TIMEOUT: 3.0
      CORS_BASE_URI: http://docker.dev:8000
      PROMETHEUS_USER: prometheus_dev_user
      PROMETHEUS_PASSWORD: prometheus_dev_password
      CACHE_KEY_SALT: dev_salt
      DEBUGGING: yeah
      REDIS_HOST: redis
      REDIS_PORT: "6379"

    depends_on:
     - redis
     - giantswarmmockapi
     - prometheus

  prometheus:
    image: registry.giantswarm.io/giantswarm/fake-metrics-prometheus:latest
    ports:
      - "9090:9090"
    links:
      - fake-metrics-node

  fake-metrics-node:
    image: registry.giantswarm.io/giantswarm/fake-metrics-node:latest

  domain-validator:
    image: registry.giantswarm.io/giantswarm/domain-validator
    depends_on:
      - nsqd
      - couchdb
    ports:
      - "5001:5000"
    volumes:
      - ./certificates:/certs
    environment:
      NSQD_HTTP_ENDPOINT: http://nsqd:4151
      DEBUGGING: "YEAH"
      GIANTSWARM_API_URI: http://giantswarmmockapi:8000
      GIANTSWARM_ADMIN_TOKEN:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CORS_BASE_URI: http://docker.dev:8000
      CACHE_KEY_SALT: 793857234kjnsdfkjn128ed3ubnkdn2398e
      TOPIC_DOMAIN_VALIDATION: domain_validation
      COUCHDB_USER: meister
      COUCHDB_PASSWORD: a27r0df0912nbogd094t
      COUCHDB_HOST: couchdb
      COUCHDB_DBNAME: domains

  couchdb:
    image: couchdb:1.6.1
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: meister
      COUCHDB_PASSWORD: a27r0df0912nbogd094t

  nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: >
      /nsqd --lookupd-tcp-address=nsqlookupd:4160
            --broadcast-address=nsqd
            --msg-timeout="100s"
            --max-msg-timeout=48h
            --verbose=true

    ports:
      - "4150:4150"
      - "4151:4151"
      - "4152:4152"

    volumes:
      - ./certificates:/certs

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    command: >
      /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"

  worker:
    image: registry.giantswarm.io/giantswarm/domain-validator-worker
    depends_on:
      - nsqlookupd
      - couchdb
    volumes:
      - ./certificates:/certs
    environment:
      LOG_LEVEL: DEBUG
      NSQLOOKUPD_HTTP_ADDRESSES: "nsqlookupd:4161"
      TOPIC: domain_validation
      CHANNEL: default
      MAX_TASK_AGE: "86400"
      MAX_BACKOFF_DURATION: "60"
      MAX_TRIES: "1000"
      MAX_IN_FLIGHT: "1"
      POLL_INTERVAL: "5"
      NAMESERVERS: 8.8.8.8 8.8.4.4
      DNS_TIMEOUT: "5"
      DNS_LIFETIME: "7"
      COUCHDB_USER: meister
      COUCHDB_PASSWORD: a27r0df0912nbogd094t
      COUCHDB_HOST: couchdb
      COUCHDB_DBNAME: domains
