apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: happa
  namespace: giantswarm
  labels:
    app: happa
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: happa
    spec:
      volumes:
        - name: giantswarm-cert
          secret:
            secretName: giantswarm-cert
      containers:
      - name: happa
        image: registry.giantswarm.io/giantswarm/happa:%%DOCKER_TAG%%
        volumeMounts:
        - name: giantswarm-cert
          mountPath: /etc/nginx/certs
          readOnly: true
        env:
        - name: PASSAGE_ENDPOINT
          value: https://passage-k8s.giantswarm.io
        - name: API_ENDPOINT
          value: https://api-k8s.giantswarm.io
        - name: DESMOTES_ENDPOINT
          value: https://desmotes-k8s.giantswarm.io
        - name: ENVIRONMENT
          value: kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
      imagePullSecrets:
      - name: circleci-giantswarm-registry