apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: happa
  namespace: giantswarm
  labels:
    app: happa
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: happa-g8s.giantswarm.io
    http:
      paths:
      - backend:
          serviceName: happa
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - happa-g8s.giantswarm.io